app:
  policy-name: note
server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9080/auth/realms/jhipster
          # issuer-uri: http://localhost:9080/auth/realms/jhipster