server:
  port: 8082
  forward-headers-strategy: framework # https://github.com/spring-projects/spring-boot/commit/959e161555a147cac812915b1677abb46e3a860b
spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: keycloak
            client-id: web_app
            client-secret: web_app
            scope: openid,profile,email,offline_access
        provider:
          keycloak:
            issuer-uri: http://keycloak:9080/auth/realms/jhipster
            # issuer-uri: http://localhost:9080/auth/realms/jhipster
  cloud:
    gateway:
      default-filters:
        # - TokenRelay=
        # until https://github.com/spring-cloud/spring-cloud-security/issues/175 is resolved
        - TokenRelayWithTokenRefresh=
        - RemoveRequestHeader=Cookie
      routes:
        - id: note
          uri: http://localhost:8081
          predicates:
            - Path=/api/notes/**
        - id: policy-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/policy-evaluation/**
          filters:
            - RemoveResponseHeader=Set-Cookie # or else policy-service's XSRF-TOKEN clobbers the gateway's!